### ISSUE TITLE
Demo? :)

### ISSUE THREAD

**Issue by addyosmani** [wmsmacdonald/delta-cache-browser#2]
Hey @wmsmacdonald. Over on the Chrome team we've been kicking around a few ideas for delta upgrading using Service Workers and came across your repo. 

Is there a demo available where you're using delta patching + this setup/your express middleware bits together that folks can check out?

Cheers!

**Comment by wmsmacdonald** [comment]
@addyosmani Hi, thanks for checking out my project! I don't have a live demo currently but I've been thinking about putting one together for a while. You can expect one in a few days.

**Comment by addyosmani** [comment]
Awesome. Thanks!

**Comment by wmsmacdonald** [comment]
The demo is done but not live yet, to see it run `npm run-script run-demo`. The demo uses the more flexible [delta-cache-node](https://github.com/wmsmacdonald/delta-cache-node) and not the Express middleware [delta-cache-express](https://github.com/wmsmacdonald/delta-cache-express). I do plan to change the demo to using the Express middleware, but first I want to improve the API for the Express project so that it is more in line with other middleware (particularly [compression](https://www.npmjs.com/package/compression)).

I should have the demo code deployed live in a couple days. If you are looking for an example with server support for Express, you might as well wait until I finish the API changes in the Express project, which should be a week or so.
